// Cities and Areas for Pakistan Marketplace
// Based on OLX Pakistan structure

export interface CityAreas {
  city: string;
  areas: string[];
}

export const citiesWithAreas: CityAreas[] = [
  {
    city: 'Karachi',
    areas: [
      'All Areas',
      'DHA Defence',
      'Gulshan-e-Iqbal',
      'Clifton',
      'North Nazimabad',
      'Korangi',
      'Malir',
      'Landhi',
      'Shah Faisal Colony',
      'Gulistan-e-Jauhar',
      'Federal B Area',
      'Saddar',
      'PECHS',
      'Tariq Road',
      'Bahadurabad',
      'Gulberg',
      'Liaquatabad',
      'Nazimabad',
      'Orangi Town',
      'Surjani Town',
      'North Karachi',
      'New Karachi',
      'Buffer Zone',
      'Water Pump',
      'FB Area',
      'Gulshan-e-Maymar',
      'Scheme 33',
      'Scheme 45',
      'Saadi Town',
      'Gadap Town',
      'Shahra-e-Faisal',
      'Shahra-e-Quaideen',
      'M A Jinnah Road',
      'Garden',
      'Kharadar',
      'Mithadar',
      'Lyari',
      'Keamari',
      'SITE Area',
      'Shershah',
      'Ittehad Town',
      'Baldia Town',
      'Manghopir',
      'Maripur',
      ' Ibrahim Hyderi',
      'Rehri',
      'Cattle Colony',
      'Port Qasim',
    ],
  },
  {
    city: 'Lahore',
    areas: [
      'All Areas',
      'DHA Defence',
      'Gulberg',
      'Johar Town',
      'Model Town',
      'Cantt',
      'Allama Iqbal Town',
      'Garden Town',
      'Faisal Town',
      'Ichhra',
      'Shadman',
      'Township',
      'Wapda Town',
      'Bahria Town',
      'Eden',
      'Punjab Society',
      'Cavalry Ground',
      'Siddiqia Colony',
      'Samanabad',
      'Gulshan-e-Ravi',
      'Sabzazar',
      'Mustafa Town',
      'Wahdat Colony',
      'Pindi Stop',
      'Multan Road',
      'Thokar Niaz Baig',
      'Raiwind Road',
      'Canal Road',
      'Mall Road',
      'Anarkali',
      'Data Darbar',
      'Shahdara',
      'Badami Bagh',
      'Sanda',
      'Kot Lakhpat',
      'Green Town',
      'Valencia',
      'Awan Town',
      'Marghzar Colony',
      'Chungi Amar Sadhu',
      'Bhogiwal',
      'Tajpura',
      'Harbanspura',
      'Baghbanpura',
      'Kamahan',
      'Defence Road',
      'Bedian Road',
      'Barki Road',
    ],
  },
  {
    city: 'Islamabad',
    areas: [
      'All Areas',
      'DHA Defence',
      'Bahria Town',
      'G-6',
      'G-7',
      'G-8',
      'G-9',
      'G-10',
      'G-11',
      'G-12',
      'G-13',
      'G-14',
      'G-15',
      'G-16',
      'F-6',
      'F-7',
      'F-8',
      'F-9',
      'F-10',
      'F-11',
      'F-12',
      'E-7',
      'E-8',
      'E-9',
      'E-10',
      'E-11',
      'E-12',
      'E-13',
      'E-14',
      'E-15',
      'E-16',
      'I-8',
      'I-9',
      'I-10',
      'I-11',
      'I-12',
      'I-13',
      'I-14',
      'H-8',
      'H-9',
      'H-10',
      'H-11',
      'H-12',
      'H-13',
      'B-17',
      'D-12',
      'D-17',
      'Bani Gala',
      'Bharakahu',
      'Chak Shahzad',
      'Shah Allah Ditta',
      'Tarnol',
      'Sihala',
      'Koral',
      'Lohi Bher',
      'Kuri Road',
      'Park Road',
      'Lehtrar Road',
      'Murree Road',
      'Peshawar Road',
      'GT Road',
      'Express Highway',
      'Srinagar Highway',
    ],
  },
  {
    city: 'Rawalpindi',
    areas: [
      'All Areas',
      'DHA Defence',
      'Bahria Town',
      'Saddar',
      'Commercial Market',
      'Satellite Town',
      'Chaklala Scheme',
      'Gulraiz',
      'Shalley Valley',
      'Westridge',
      'Tench Bhatta',
      'Lalkurti',
      'Adiala Road',
      'Kamra Road',
      'Airport Road',
      'Chakri Road',
      'Peshawar Road',
      'GT Road',
      'Murree Road',
      'IJP Road',
      'Kashmir Road',
      'Sadiqabad',
      'Dhoke Kala Khan',
      'Dhoke Mangtal',
      'Dhoke Elahi Baksh',
      'Misrial Road',
      'Range Road',
      'Askari',
      'Fazaia Colony',
      'Gulshanabad',
      'Khanna Pul',
      'Shamsabad',
      'Rehmanabad',
      'Double Road',
      '6th Road',
      '7th Road',
      '8th Road',
      'Chandni Chowk',
      'Committee Chowk',
      'Liaquat Bagh',
      'Raja Bazaar',
      'Kohinoor',
      'Waris Khan',
      'Banni',
      'Marir Hassan',
      'Kuri Road',
    ],
  },
  {
    city: 'Faisalabad',
    areas: [
      'All Areas',
      'D Ground',
      'Peoples Colony',
      'Madina Town',
      'Jaranwala Road',
      'Sargodha Road',
      'Canal Road',
      'Susan Road',
      'Satiana Road',
      'Jhang Road',
      'Samundari Road',
      'Sheikhupura Road',
      'Millat Town',
      'Gulberg',
      'Iqbal Town',
      'Mansoorabad',
      'Nishatabad',
      'Narwala Road',
      'Kohinoor City',
      'Civil Lines',
      'Karkhana Bazaar',
      'Chiniot Bazaar',
      'Amin Town',
      'Razaabad',
      'Sitara Colony',
      'Wapda City',
      'Green Town',
      'Eden Valley',
      'Citi Housing',
    ],
  },
  {
    city: 'Gujranwala',
    areas: [
      'All Areas',
      'Satellite Town',
      'Model Town',
      'Civil Lines',
      'Gulshan-e-Iqbal',
      'Wapda Town',
      'Garden Town',
      'Peoples Colony',
      'Sialkot Road',
      'Grand Trunk Road',
      'Hafizabad Road',
      'Kamoke Road',
      'Nowshera Road',
      'Shaheenabad',
      'Rahwali',
      'Qila Didar Singh',
      'Wazirabad',
      'Ghakhar',
      'Aroop',
      'Nandipur',
      'Khiali',
      'Daska Road',
      'Pasrur Road',
      'Alipur Chatha',
      'Kalaske',
      'Gakhar Mandi',
    ],
  },
  {
    city: 'Sialkot',
    areas: [
      'All Areas',
      'Cantt',
      'Model Town',
      'Defence Road',
      'Neka Pura',
      'Rangpura',
      'Kashmir Road',
      'Paris Road',
      'Kutchery Road',
      'Shahab Pura',
      'Ugoki',
      'Sambrial',
      'Daska',
      'Pasrur',
      'Zafarwal',
      'Shakargarh',
      'Baddomalhi',
      'Chawinda',
      'Bharath',
      'Head Marala',
      'Ugoke',
      'Adamke',
    ],
  },
  {
    city: 'Multan',
    areas: [
      'All Areas',
      'Cantt',
      'Gulgasht Colony',
      'Shah Rukn-e-Alam Colony',
      'Bosan Road',
      'Vehari Road',
      'Khanewal Road',
      'Larr',
      'Shujabad',
      'Jalalpur Pirwala',
      'Qadirpur Ran',
      'Mumtazabad',
      'New Multan',
      'Old Shujaabad Road',
      'Northern Bypass',
      'Southern Bypass',
      'Industrial Estate',
      'Chowk Kumharan',
      'Haram Gate',
      'Delhi Gate',
      'Pak Gate',
      'Daulat Gate',
      'Hussain Agahi',
      'Ghanta Ghar',
      'Nawan Shehr',
      'Cantt Road',
      'Double Phatak',
      'Qasim Bela',
      'Wapda Town',
      'DHA Multan',
      'Royal Orchard',
    ],
  },
  {
    city: 'Peshawar',
    areas: [
      'All Areas',
      'University Road',
      'Hayatabad',
      'Cantt',
      'Saddar',
      'Qissa Khwani Bazaar',
      'Hashtnagri',
      'Gulbahar',
      'Faqeerabad',
      'Nothia',
      'Kohati Gate',
      'Bana Mari',
      'Board Bazaar',
      'Firdous',
      'Shami Road',
      'Dalazak Road',
      'Ring Road',
      'Charsadda Road',
      'Kohat Road',
      'Warsak Road',
      'Jamrud Road',
      'Bara Road',
      'GT Road',
      'Phase 1',
      'Phase 2',
      'Phase 3',
      'Phase 4',
      'Phase 5',
      'Phase 6',
      'Phase 7',
      'Phase 8',
      'Regi Model Town',
      'DHA Peshawar',
    ],
  },
  {
    city: 'Quetta',
    areas: [
      'All Areas',
      'Jinnah Road',
      'Zarghoon Road',
      'Airport Road',
      'Sariab Road',
      'Brewery Road',
      'Arbab Karam Khan Road',
      'Mastung Road',
      'Qambrani Road',
      'Qta-Loralai Road',
      'Qta-Chaman Road',
      'Qta-Zhob Road',
      'Satellite Town',
      'Model Town',
      'Jafferabad',
      'Chiltan Housing',
      'Saddar',
      'Liaquat Bazaar',
      'Kandahari Bazaar',
      'Mekangi Road',
      'Hazar Ganji',
      'Kuchlak',
      'Kanozai',
      'Pishin',
      'Chaman',
      'Mastung',
      'Kalat',
      'Khuzdar',
      'Loralai',
      'Zhob',
    ],
  },
  {
    city: 'Hyderabad',
    areas: [
      'All Areas',
      'Latifabad',
      'Qasimabad',
      'City Area',
      'Saddar',
      'Hirabad',
      'Thandi Sarak',
      'Auto Bhan Road',
      'Hyderabad Bypass',
      'Tando Adam Road',
      'Matiari Road',
      'Moro Road',
      'Dadu Road',
      'Jamshoro Road',
      'Kotri Road',
      'Badin Road',
      'Mirpurkhas Road',
      'Sakrand Road',
      'Tando Allahyar Road',
      'Tando Muhammad Khan Road',
      'Phase 1',
      'Phase 2',
      'Phase 3',
      'Gulistan-e-Sarmast',
      'Citizen Colony',
      'Wadhu Wah',
      'Tando Fazal',
      'Bhit Shah',
    ],
  },
  {
    city: 'Sargodha',
    areas: [
      'All Areas',
      'University Road',
      'Satellite Town',
      'Civil Lines',
      'Cantt',
      'Mianwali Road',
      'Faisalabad Road',
      'Lahore Road',
      'Jhang Road',
      'Bhalwal Road',
      'Kot Momin Road',
      'Sillanwali Road',
      'Shaheenabad',
      'Islamabad Colony',
      'Millat Colony',
      'Gulshan-e-Iqbal',
      'Model Town',
      'Shadman Colony',
      'University Town',
      'Green Town',
      'Bhera',
      'Shahpur',
      'Sahiwal',
      'Kot Momin',
      'Bhalwal',
      'Sillanwali',
    ],
  },
  {
    city: 'Gujrat',
    areas: [
      'All Areas',
      'G T Road',
      'Jalalpur Jattan Road',
      'Kunjah Road',
      'Saraialamgir Road',
      'Bhimber Road',
      'Kotla Road',
      'Shadman Colony',
      'Civil Lines',
      'Model Town',
      'Satellite Town',
      'Aziz Colony',
      'Rehman Colony',
      'Gulshan-e-Iqbal',
      'Madina Colony',
      'Green Valley',
      'Wapda Town',
      'Lalamusa',
      'Kharian',
      'Jalalpur Jattan',
      'Kunjah',
      'Saraialamgir',
      'Kotla',
      'Dinga',
    ],
  },
  {
    city: 'Bahawalpur',
    areas: [
      'All Areas',
      'Model Town A',
      'Model Town B',
      'Model Town C',
      'Satellite Town',
      'Cantt',
      'Civil Lines',
      'Fawara Chowk',
      'Shahi Bazaar',
      'Farid Gate',
      'Lahore Road',
      'Multan Road',
      'Rahim Yar Khan Road',
      'Dera Nawab Road',
      'Hasilpur Road',
      'Khanewal Road',
      'Bahawalnagar Road',
      'Fort Derawar Road',
      'Ahmadpur Road',
      'Lodhran Road',
      'Green City',
      'Gulshan-e-Iqbal',
      'University Road',
      'Airport Road',
      'Hasilpur',
      'Ahmadpur East',
      'Rahim Yar Khan',
      'Khanpur',
      'Sadiqabad',
      'Dera Nawab',
    ],
  },
  {
    city: 'Sahiwal',
    areas: [
      'All Areas',
      'Farid Town',
      'Civil Lines',
      'Gulshan-e-Iqbal',
      'Model Town',
      'Satellite Town',
      'Chichawatni Road',
      'Okara Road',
      'Multan Road',
      'Lahore Road',
      'Harappa Road',
      'Yousafwala Road',
      'Qadirabad Road',
      'Noor Shah Road',
      'Green Town',
      'Wapda Town',
      'Chichawatni',
      'Okara',
      'Arifwala',
      'Pakpattan',
    ],
  },
];

// Get all cities
export function getAllCities(): string[] {
  return citiesWithAreas.map((c) => c.city);
}

// Get areas for a city
export function getAreasForCity(city: string): string[] {
  const cityData = citiesWithAreas.find((c) => c.city === city);
  return cityData?.areas || [];
}

// Check if city exists
export function cityExists(city: string): boolean {
  return citiesWithAreas.some((c) => c.city === city);
}

// Check if area exists in city
export function areaExistsInCity(city: string, area: string): boolean {
  const areas = getAreasForCity(city);
  return areas.includes(area);
}
